### ISSUE TITLE
Need Help?

### ISSUE THREAD

**Issue by amark** [relaxjs/relax-db#1]
Sorry to open an issue, wasn't sure about your email.

I'm the author of gun and noticed you using it! But also haven't talked/chatted to you yet (unless we bumped into each other at a conference?) and just wanted to chime in and see what's up? (Feel free to close this issue! Also: https://gitter.im/amark/gun )

**Comment by tokyo-jesus** [comment]
First off, thanks for all of your work; Gun is great! My email is in my profile, I'd love to be in touch :)

My goal with relax js is to create a toolkit for building peer-to-peer web applications. My plans for this module include building some extensions on top of Gun to provide additional indexing and querying tools.

There is a lot to do, and a lot left to think about. I'm open to contributions of any kind.

**Comment by amark** [comment]
That sounds awesome! I'll follow up with an email and close this thread here. :)
